### ISSUE TITLE
Add SCC COCOMO and Complexity Metrics

### ISSUE THREAD

**Issue by IsaacMilarky** [DSACMS/metrics#141]
## Issue Report

Add SCC COCOMO and Complexity Metrics

### Expected behavior

The repository metrics report page as well as the org metrics report page should display complexity and COCOMO metrics to communicate cost estimates and complexity to the user. We will use the [boyter/scc](https://github.com/boyter/scc) tool in order to generate this part of the report. 

Example output:
```
───────────────────────────────────────────────────────────────────────────────
Language                 Files     Lines   Blanks  Comments     Code Complexity
───────────────────────────────────────────────────────────────────────────────
Markdown                     6       223       72         0      151          0
JavaScript                   2       482       76        31      375         78
JSON                         1       367        0         0      367          0
───────────────────────────────────────────────────────────────────────────────
Total                        9      1072      148        31      893         78
───────────────────────────────────────────────────────────────────────────────
Estimated Cost to Develop (organic) $23,987
Estimated Schedule Effort (organic) 3.33 months
Estimated People Required (organic) 0.64
───────────────────────────────────────────────────────────────────────────────
Processed 33448 bytes, 0.033 megabytes (SI)
───────────────────────────────────────────────────────────────────────────────
```

### Actual behavior

These metrics are missing.

**Comment by IsaacMilarky** [comment]
7/1:

- ACTION: schedule meeting to discuss implementing scc metrics in the metrics backend

**Comment by IsaacMilarky** [comment]
7/3:

- Follow up later in the week

**Comment by IsaacMilarky** [comment]
7/12:

- Progress has been made on COCOMO script and action 
- Draft PR to add the Scc metrics in progress: https://github.com/DSACMS/metrics/pull/176/
- Current plan is to use this script until the data is available in Augur at which point we will switch
- Will also switch to using this script on private repositories instead of public

**Comment by natalialuzuriaga** [comment]
7/15:
- Ready for Isaac's review @IsaacMilarky 
- Attempting to test GH action, @IsaacMilarky for guidance
- Hopefully will merge in EoW

**Comment by natalialuzuriaga** [comment]
7/19:
- Messaged Isaac regarding review, he will get back next week to resolve. Works on Brandon's local but not Isaac's

**Comment by decause-gov** [comment]
7/22:
- PR was just merged into Dev.
- Had some issues running on GFE, but it ran on other machine.
- Did not work for some repos, populated for most, but not for all. Perhaps cloning timeouts? (File a ticket if this isn't a one-off bug.)
- Could be interesting hacks to optimize (iterative step, continually grabs repo, only clones once per job, etc...) Could do separate jobs for each repos.
- @Firebird1029 Will look into issue, meet with Isaac (there are ways to test gh-actions locally, but, not most mature. Best way is to fork repo and test.)
- Suggestions: Fork repo, enable gh-action for that repo, and then ff to dev, and test in your own repo to see if it works in that env.
- ACTION: Brainstorm with decause about command-line flags.

**Comment by decause-gov** [comment]
7/26:
- ACTION: Meeting on the books for 07/26 w/ @decause-gov and @IsaacMilarky 
- Experimented with commandline flags, working on final list now.

**Comment by decause-gov** [comment]
07/29:
- Meeting with Isaac about debugging the 'unable to clone' issues
- Just met with decause to talk about outputting json for new flags
- BONUS: file a ticket on upstream scc repo for missing functionality for --dryness on html output?
- Goal: Send a PR by MoW.

**Comment by Firebird1029** [comment]
PR is ready for review: https://github.com/DSACMS/metrics/pull/196 @decause-gov @IsaacMilarky @natalialuzuriaga

**Comment by decause-gov** [comment]
08/02:
- PR merged! https://github.com/DSACMS/metrics/pull/196 🥥
