### ISSUE TITLE
Add Libyear Metric and Reports

### ISSUE THREAD

**Issue by IsaacMilarky** [DSACMS/metrics#142]
## Issue Report

Add Libyear Metric and Reports

### Expected behavior

The repository metrics reports pages should have a breakdown of the key dependencies of each project that includes a measure of the ['libyears'](https://chaoss.community/kb/metric-libyears/)of that repository. This adds to the risk management side of the metrics website and can be used to diagnose maintenance problems. 

### Actual behavior

This metric is missing.

**Comment by decause-gov** [comment]
07/29:
- Meet with Isaac to review the Augur Endpoint for libyears
- GOAL: Add to metrics project by EoW

**Comment by decause-gov** [comment]
08/02:
- Backburnered to work on scorecard and other tickets.

**Comment by natalialuzuriaga** [comment]
10/07:
- Isaac is working on this! Libyears in the backend, needs a frontend

**Comment by IsaacMilarky** [comment]
10/11:

- Libyear metric and report charts are in dev now
- https://github.com/DSACMS/metrics/pull/255
- https://github.com/DSACMS/metrics/pull/245
