### ISSUE TITLE
Create GitHub Action to Generate OSSF Scorecard Report for Internal Repositories

### ISSUE THREAD

**Issue by IsaacMilarky** [DSACMS/metrics#144]
## Issue Report

Create GitHub Action to Generate OSSF Scorecard Report for Internal Repositories

### Expected behavior

We should create a new GitHub Action that uses the OSSF scorecard CLI tool to generate metrics about internal repositories to save on internal repos instead of adding the information to the OSSF scorecard api like you should with a public repository. 

### Actual behavior

This action is missing.

**Comment by Firebird1029** [comment]
https://github.com/DSACMS/metrics/pull/199

**Comment by decause-gov** [comment]
08/02:
- PR merged! https://github.com/DSACMS/metrics/pull/199 📝
