### ISSUE TITLE
Creating a Glossary Page

### ISSUE THREAD

**Issue by natalialuzuriaga** [DSACMS/metrics#145]
## MENTOR
- @natalialuzuriaga  
- SWE Fellow, USDigitalCorps
- dm on slack, #wg-government on CHAOSS.community slack, 

## BRIEF DESCRIPTION
Some of the metrics website's primary users are non-technical folks such as project managers, product managers, designers and agency leadership, who may be unfamiliar with certain technical terms + graphs such as Git Terminology, repository metrics + data visualizations. Currently, the metrics website provides no background on these terms and meaning of the metrics + visualizations, thus it impacts their understanding when reading organization + repository reports.

We'd like to create a glossary page so the users know what certain terms, metrics, and visualizations mean on organization + repository reports.

Some ideas include but are not limited to:
- Creating a dedicated Glossary Page with definitions of technical terms and metrics. 
- Information icons next to terms or graph titles that would show a popup with a description upon hover would help too, since the user is provided context instantly. 

## SCOPING
- 2 weeks

## SKILLS NEEDED
Front-end, Webdev

## REQUIRED DELIVERABLES
- Creating design mockups of designs, conducting user research maybe
- Frontend development with coordination with backend devs
- Testing

## DESIRED DELIVERY WINDOW
- Any

## NOTES/INSPO
Any feedback and ideas on this issue are welcome!

# ACKNOWLEDGEMENTS
- [X] - Yes, I agree to spend file a project proposal ticket
- [x] - Yes, I agree this project falls within a 2 week or less (ideally less) scope of time
- [x] - Yes, I agree to spend an hour per week of office hours and 1x1 mentoring
- [x] - Yes, I agree to spend an hour at the end of the sprint for filling out a Retro Template

**Comment by decause-gov** [comment]
09/10:

Here's a list of tasks we'd like @noobnoob06 to take on:
- Create an example Gdoc with the look/feel for how we want Definitions to look on the page
- OSPO will suggest a couple, Keni will suggest a couple.
- Markdown-ify the page, test in a viewer (VSCode markdown extension, Markdown previewer if that breaks)
- Once the markdown looks good in testing, @noobnoob06 will submit a PR for review

Later, after glossary success:
- separate ticket for converting repo-scaffolder .pdf files into markdown

**Comment by decause-gov** [comment]
09/20:
- Added terms to glossary page
- Added headings/sections
- Defined the orgs, but need descriptions for the other orgs (see chat)
- ACTION: Will commit to repo and send a PR next week!

**Comment by IsaacMilarky** [comment]
9/30:

- Metrics glossary PR merged: https://github.com/DSACMS/metrics/pull/235
- Link to the glossary on the metrics website?
- Closed for now, will create a new loop to follow up on potential next steps.
