### ISSUE TITLE
Project Rotation: Age of Project 

### ISSUE THREAD

**Issue by decause-gov** [DSACMS/metrics#149]
## MENTOR
- @IsaacMilarky 
- SWE Fellow, USDigitalCorps
- #wg-ospo on CHAOSS.community slack.

## BRIEF DESCRIPTION
We would like to fetch data on age of project using the GitHub API and display this information in the repository's report.

## SCOPING
- 1-3 days

## SKILLS NEEDED
Front-end, Back-end, Webdev

## REQUIRED DELIVERABLES
1. Use the GitHub API to fetch data on age of a repository
2. Add this information to the repository's json file.
3. Identify ways to show this data in the report (plain number, range, tag). May require making some Figma designs.
4. Add to repository report.

## DESIRED DELIVERY WINDOW
- Any

## NOTES/INSPO

# ACKNOWLEDGEMENTS
- [X] - Yes, I agree to spend file a project proposal ticket
- [ ] - Yes, I agree this project falls within a 2 week or less (ideally less) scope of time
- [ ] - Yes, I agree to spend an hour per week of office hours and 1x1 mentoring
- [ ] - Yes, I agree to spend an hour at the end of the sprint for filling out a Retro Template

**Comment by decause-gov** [comment]
07/29:
- Got the 'created-at' property from GraphQL API
- Discussing with Isaac on Monday 1x1 w/Isaac on Monday!
- IDEA: add that query to existing GraphQL Query!

**Comment by decause-gov** [comment]
07/29:
- Meeting with Isaac to discuss today.
- GOAL: Ship the PR adding metrics to backend by EoD today/tomorrow.

**Comment by Firebird1029** [comment]
PR is ready for review: https://github.com/DSACMS/metrics/pull/197

@IsaacMilarky Is there anything I need to change on the frontend to correctly display this metric?

**Comment by decause-gov** [comment]
08/02:
- PR is merged! https://github.com/DSACMS/metrics/pull/197 👵
