### ISSUE TITLE
Project Rotation: Predominant Langauges

### ISSUE THREAD

**Issue by decause-gov** [DSACMS/metrics#150]
## MENTOR
- @IsaacMilarky 
- SWE Fellow, USDigitalCorps
- #wg-ospo on CHAOSS.community slack.

## BRIEF DESCRIPTION
We would like to fetch data on predominant languages of a repository using the GitHub API and include a visualization displaying this information in the repository's report. 

## SCOPING
- 1-3 days

## SKILLS NEEDED
Front-end, Back-end, Webdev, Data

## REQUIRED DELIVERABLES
1. Use the GitHub API to fetch data on predominant languages of a repository
https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-repository-languages
2. Add this information to the repository's json file.
3. Use Pygals or another visualization library to create a visualization of this data.
4. Add visualization to repository report.

## DESIRED DELIVERY WINDOW
- Any

## NOTES/INSPO

# ACKNOWLEDGEMENTS
- [X] - Yes, I agree to spend file a project proposal ticket
- [ ] - Yes, I agree this project falls within a 2 week or less (ideally less) scope of time
- [ ] - Yes, I agree to spend an hour per week of office hours and 1x1 mentoring
- [ ] - Yes, I agree to spend an hour at the end of the sprint for filling out a Retro Template

**Comment by decause-gov** [comment]
@RicardoZamora01 
@Firebird1029 
Def stay in the loop on this one too as a good first rotation in the Metrics Stack.

**Comment by IsaacMilarky** [comment]
7/8:

- Backburner for now
- ACTION: run the metrics stack locally or just look at it

**Comment by IsaacMilarky** [comment]
7/12:

- Read up on API and PyGals
- Look at defined metrics classes and Ricardo's PR into metrics
- ACTION: Continue research into metrics website.

**Comment by natalialuzuriaga** [comment]
7/15:
- Now we know what json file to add data too
- Continuing work this week

**Comment by natalialuzuriaga** [comment]
7/19:
- Sill working on it, repo is cloned

**Comment by decause-gov** [comment]
07/26:
- Met with @IsaacMilarky yesterday
- Steps 1 and 2 completed!
- Working on Step 3 (Pygals)
- Q: For visualizations, create a new python file?
- A: Let's convert this ticket to just the backend. @RicardoZamora01 added a visualization for another front-end metric viz, so you can just take the same approach. `gen_graphs.py` is the right place likely. There's a script for each step: getting data, generating graphs, generating reports. Adding a new function in `gen_graphs.py` and `genreports.py` should be in a separate ticket.
- IDEA: the front-end will vary slightly depending on what is returned by languages, so accounting for that will be the challenge to keep in mind.
- IDEA: Explore 'half-donut' as a way to viz this! https://www.pygal.org/en/stable/documentation/types/pie.html

**Comment by decause-gov** [comment]
07/29:
- spoke with Isaac about testing changes, will look into this.
- Need to continue researching testing of changes, then create PR
- IDEA: Adding metric, comment out other metrics, commit local, and see if it shows up.
- IDEA: actually do pytests! 
- Goal: Send a PR after testing changes

**Comment by decause-gov** [comment]
08/02:
- VSCode/Git issues, but working on a fix to publish the branch. Need to do some git-surgery. 
- Spoke with Isaac yesterday, should be good to send.
- IDEA: Post in #dsac-eng if you get stuck.
- GOAL: PR by EoB

**Comment by CreativeNick** [comment]
PR: https://github.com/DSACMS/metrics/pull/208

**Comment by CreativeNick** [comment]
08/07:
- PR merged!
