### ISSUE TITLE
Project Rotation: Top Committer by Org

### ISSUE THREAD

**Issue by decause-gov** [DSACMS/metrics#155]
## MENTOR
- @IsaacMilarky 
- USDC Fellow, OSPO
- @MURT on slack

## BRIEF DESCRIPTION
Have:
- API Endpoint in Augur.io
- Data in the metrics repo `Metrics/app/site/_data/{ORG}/{ORG}_data.json`

Needs:
- Front-end dataviz for the site

## SCOPING
- days

## SKILLS NEEDED
Front-end, Python, JSON Knowledge

## REQUIRED DELIVERABLES
1. Add new function to generate visualization appropriate for data to `scripts/gen_graphs.py`
2. Edit the file to use the new function to generate the new visualization
3. Make sure that the `graph-section.liquid` file generates the graph properly 

## DESIRED DELIVERY WINDOW
- Any

## NOTES/INSPO
Come up with a good way to visualize the top people that have commited to a GitHub Organization. 

# ACKNOWLEDGEMENTS
- [X] - Yes, I agree to spend file a project proposal ticket
- [X] - Yes, I agree this project falls within a 2 week or less (ideally less) scope of time
- [X] - Yes, I agree to spend an hour per week of office hours and 1x1 mentoring
- [X] - Yes, I agree to spend an hour at the end of the sprint for filling out a Retro Template

**Comment by natalialuzuriaga** [comment]
7/15:
- Starting on this one this week

**Comment by natalialuzuriaga** [comment]
7/19:
- Able to generate the graph to bar chart, writes it into the directory doesn't render onto the website

**Comment by RicardoZamora01** [comment]
Do we want to keep or remove "other_contributors"?

**Comment by decause-gov** [comment]
7/22:
- Progress looks great!
- we're able to generate a graph, need to fix some front-end bugs to render properly.
- DECISION: Keep other contributors :) 🧑‍⚖ 
- Goal: Ship this week!
