### ISSUE TITLE
Project Rotation: Update code.json fields to use camel case

### ISSUE THREAD

**Issue by natalialuzuriaga** [DSACMS/metrics#220]
## MENTOR
- @natalialuzuriaga 
- USDC SWE Fellow, OSPO
- Slack

## BRIEF DESCRIPTION
As I'm going through adding the required fields to code.json, one of the things that we have to update with our current implementation is to change all field names from snake case to camel case (example being 1project_type` to `projectType`). This is due to code.json using camel case so we'd like to follow this pattern.

## SCOPING
- 1-2 days

## SKILLS NEEDED
Front-end

## REQUIRED DELIVERABLES
Make as clear of a step-by-step list as you can
1. In repo-scaffolder, update code.json fields in all tiers to camelCase.
2. In all repos that have a code.json, update fields to camelCase.
3.  Update accordingly so this change works with the metrics frontend.

## DESIRED DELIVERY WINDOW
- Any

## NOTES/INSPO

# ACKNOWLEDGEMENTS
- [X] - Yes, I agree to spend file a project proposal ticket
- [X] - Yes, I agree this project falls within a 2 week or less (ideally less) scope of time
- [X] - Yes, I agree to spend an hour per week of office hours and 1x1 mentoring
- [X] - Yes, I agree to spend an hour at the end of the sprint for filling out a Retro Template

**Comment by decause-gov** [comment]
08/15:
- 3 out of 4 merged.
- Waiting on Metrics ticket.
- Working on updating the Frontend to accept the new fields.
- Merged:
Repo Scaffolder: https://github.com/DSACMS/repo-scaffolder/pull/142
Open: https://github.com/DSACMS/open/pull/47
DedupliFHIR: https://github.com/DSACMS/dedupliFHIR/pull/121

Not yet Merged:
Metrics: https://github.com/DSACMS/metrics/pull/222

Update Metrics Frontend + API: 
https://github.com/DSACMS/metrics/pull/223

- Goal: Still need to review updatemetrics front-end API

**Comment by decause-gov** [comment]
08/30:
https://github.com/DSACMS/metrics/pull/223 Merged
https://github.com/DSACMS/metrics/pull/222 Merged
