### ISSUE TITLE
Front-end: Project Age

### ISSUE THREAD

**Issue by decause-gov** [DSACMS/metrics#230]
## BRIEF DESCRIPTION
Currently, the backend uses the GitHub API to fetch information about a project's age using `created_at`. Create a frontend to display this information in the report page.

## SKILLS NEEDED
Frontend

## REQUIRED DELIVERABLES
1. Using the `created_at` field located in a repo's `*_data.json` file, calculate the age of project.
2. Display this information in the project's report page. This can be in the form of a number or Pygals visualization. If you'd like, feel free to brainstorm and make Figma mockups to explore how this should be shown in the report. The team would be happy to give feedback.

## NOTES/INSPO
Data found here: https://github.com/DSACMS/metrics/blob/main/app/site/_data/DSACMS/metrics/metrics_data.json#L245

**Comment by IsaacMilarky** [comment]
9/30:

- @DinneK will start to look at this ticket this week
- We will discuss the metrics site in general in the Metrics V3 planning meeting today

**Comment by IsaacMilarky** [comment]
10/11:

- @IsaacMilarky requested changes that @sachin-panayil will push commits for 
- ACTION: @IsaacMilarky re-review the PR: https://github.com/DSACMS/metrics/pull/254
- ACTION: Test as mobile 🎏 
- If it doesn't show in mobile then re-think a bit

**Comment by IsaacMilarky** [comment]
10/15:

- Merged PR!: https://github.com/DSACMS/metrics/pull/254
- Now we also have a toggle option.
