### ISSUE TITLE
Front-end: COCOMO

### ISSUE THREAD

**Issue by decause-gov** [DSACMS/metrics#231]
## BRIEF DESCRIPTION
COCOMO is a software model that is used to estimate the cost, effort, and schedule required for software development projects. Currently, we have a GitHub workflow runs COCOMO on a repo and stores this information in the project's data.json file. Create a frontend that displays the following information in the form of numbers, tables, and/or Pygal visualizations:
- programming languages that make up the codebase with number of lines
- estimated costs of developing the project
- estimated time of developing the project
- number of people it required to develop the project.

## SKILLS NEEDED
Frontend

## REQUIRED DELIVERABLES
1. Using the `languageSummary` object located in a repo's `data.json` file, create a visualization and/or table using Pygals that displays the programming language + lines of code makeup of the codebase.  (NOTE: this may overlap with predominant languages ticket #232, work together with team to determine how to move forward with these similar data points)
2. Using `estimatedCost_low`, `estimatedScheduleMonths_low`, `estimatedPeople_low`, `estimatedCost_high`, `estimatedScheduleMonths_high`, `estimatedPeople_high` located in the repo's `data.json` file, create a visualization and/or table using Pygals that shows the ranges above. 

If you'd like, feel free to brainstorm and make Figma mockups to explore how this should be shown in the report. The team would be happy to give feedback.

## NOTES/INSPO
Data found here: https://github.com/DSACMS/metrics/blob/main/app/site/_data/DSACMS/metrics/metrics_data.json#L108

**Comment by natalialuzuriaga** [comment]
Consider using the `dryness_table` field too as well

**Comment by IsaacMilarky** [comment]
9/30:

    @DinneK  will start to look at this ticket this week
    We will discuss the metrics site in general in the Metrics V3 planning meeting today

**Comment by IsaacMilarky** [comment]
10/4:

- @DinneK  Also making good progress
- Going to be 3 charts
- Thinking about splitting some of the charts into separate tickets 
- ACTION: split this ticket up and file PRs as work is done

**Comment by natalialuzuriaga** [comment]
10/07:
- Splitting into two visualization: Pie chart, Bar chart
- Dinne is going to troubleshoot with Isaac and Sachin to fix errors

**Comment by DinneK** [comment]
10/08:
- I'm breaking this ticket into 2 parts. PR sent up for the first part.

**Comment by IsaacMilarky** [comment]
10/11:

- Done and merged!: https://github.com/DSACMS/metrics/pull/257
