### ISSUE TITLE
Front-end: COCOMO, Pt. 2

### ISSUE THREAD

**Issue by DinneK** [DSACMS/metrics#251]
## BRIEF DESCRIPTION
COCOMO is a software model that is used to estimate the cost, effort, and schedule required for software development projects. Currently, we have a GitHub workflow runs COCOMO on a repo and stores this information in the project's data.json file. Create a frontend that displays the following information in the form of numbers, tables, and/or Pygal visualizations:
- programming languages that make up the codebase with number of lines
- estimated costs of developing the project
- estimated time of developing the project
- number of people it required to develop the project.

## SKILLS NEEDED
Frontend

## REQUIRED DELIVERABLES
- Using `estimatedCost_low`, `estimatedScheduleMonths_low`, `estimatedPeople_low`, `estimatedCost_high`, `estimatedScheduleMonths_high`, `estimatedPeople_high` located in the repo's `data.json` file, create a visualization and/or table using Pygals that shows the ranges above. 

## NOTES/INSPO
Data found here: https://github.com/DSACMS/metrics/blob/main/app/site/_data/DSACMS/metrics/metrics_data.json#L108

**Comment by IsaacMilarky** [comment]
10/11:

- Broke down COCOMO into 4 charts
- Cost estimate PR is up: https://github.com/DSACMS/metrics/pull/259
- ACTION: meet to discuss merits of the proposed COCOMO charts

**Comment by IsaacMilarky** [comment]
10/15:

- Almost done nice work
- Cost estimate PR was merged: https://github.com/DSACMS/metrics/pull/259
- Still working on the time and people estimate, after issue with high and low estimates for those fields
- Time and people estimate are going to be tested with a horizontal bar chart

**Comment by decause-gov** [comment]
10/21:
- part of the Metrics v2 PR: https://github.com/DSACMS/metrics/pull/259 
- This ticket will auto-close when merged!
- Created a draft ticket, will file it in TODO column (Effort v.s. Value chart)
